server:
  # 服务端口号
  port: 8083

# spring配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: 192.168.1.51
    port: 6379
    password: root
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1ms
        max-wait: -1ms

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.hejiangnan.redis.entity

# 系统日志：可以定义具体包下的日志输出
logging:
  level:
    com.example.springboot: DEBUG
    org.hibernate: DEBUG
    org.springframework.data: DEBUG
    org.apache.ibatis: DEBUG




